#include <stdio.h>
#include <time.h>
#include <string.h>

#include "PRM.h"

//match this number with the number of tests wanting to be done/generated
#define total_tests 10


//comment this line to disable benchmarking within the PRM algorithm
#define PRM_BENCHMARKING 

#ifdef PRM_BENCHMARKING
#define PRM_NUM_TIMESTAMPS 64 //TODO: figure out how many timestamps are needed
#endif

void setCoord(coord_t* coord, int32_t X, int32_t Y, int32_t Z){
    coord->x = X;
    coord->y = Y;
    coord->z = Z;
}

void getGPSData(GPS_data_t* satellite, coord_t coords, uint32_t time){
    setCoord(&(satellite->coord), coords.x, coords.y, coords.z);
    satellite->time = time; 
}

int main(){
    
    coord_t emitter_PRM_coords, emitter_true_coords;
    coord_t sat_coords[4];
    GPS_data_t sats[4];


/* create GPS data using assuming a general default satellite radius of 20,200km and an emmitter radius 
of 6,371km (earth radius) found through online search.This scenario is assuming a situation with 4 
satellites (A,B,C,D).  */


// Read test dataset generated by test_generator.py:
int32_t X_gen[5*total_tests], Y_gen[5*total_tests], Z_gen[5*total_tests], time_gen[5*total_tests];
    FILE *file = fopen("./test_gen.txt", "r");
    if (file == NULL){
        perror("Error opening this file");
        return 1;
    }

    char line[100];
    int i = 0;
    while (fgets(line, sizeof(line), file)) {

    // skip empty string lines
        if (strlen(line) <= 1) {
            continue;
        }

    // Scan in data from file, format of the generated data is: "satellite_id X Y Z time"
        char satellite_id[5];
        //int X_gen[total_tests], Y_gen[total_tests], Z_gen[total_tests], time_gen[total_tests];
        sscanf(line, "%d %d %d %d %d", &satellite_id[i], &X_gen[i], &Y_gen[i], &Z_gen[i], &time_gen[i]);
        printf(line);
        printf("\n");

    // Show data values for each test set
        printf("Test iteration for Satellite %d:\n", satellite_id[i]);
        printf("X: %d, Y: %d, Z: %d, Time: %d\n", X_gen[i], Y_gen[i], Z_gen[i], time_gen[i]);
        i++;
        printf("%d \n", i);
    }
    fclose(file);

// Instead of using 2D array I used a loop that iterates by 5 eacch time due to how the satellites are stored in the arrays
    for(int test_num_tracker = 0; test_num_tracker < total_tests * 5; test_num_tracker+=5){

        printf("%d\n", Y_gen[test_num_tracker + 4]);
        setCoord(&sat_coords[0], X_gen[test_num_tracker], Y_gen[test_num_tracker], Z_gen[test_num_tracker]);
        setCoord(&sat_coords[1], X_gen[test_num_tracker + 1], Y_gen[test_num_tracker + 1], Z_gen[test_num_tracker + 1]);
        setCoord(&sat_coords[2], X_gen[test_num_tracker + 2], Y_gen[test_num_tracker + 2], Z_gen[test_num_tracker + 2]);
        setCoord(&sat_coords[3], X_gen[test_num_tracker + 3], Y_gen[test_num_tracker + 3], Z_gen[test_num_tracker + 3]);
        setCoord(&emitter_true_coords, X_gen[test_num_tracker + 4], Y_gen[test_num_tracker + 4], Z_gen[test_num_tracker + 4]);

        getGPSData(&sats[0], sat_coords[0], time_gen[test_num_tracker]);
        getGPSData(&sats[1], sat_coords[1], time_gen[test_num_tracker + 1]);
        getGPSData(&sats[2], sat_coords[2], time_gen[test_num_tracker + 2]);
        getGPSData(&sats[3], sat_coords[3], time_gen[test_num_tracker] + 3);

    // end of test data

        #ifdef PRM_BENCHMARKING

            //initialize timestamp array for benchmarking
            clock_t timestamps[PRM_NUM_TIMESTAMPS] = {0}; 
            printf("*Benchmarking enabled*\n\n");

        #else 

            //create dummy timestamp array
            clock_t* timestamps = NULL; 
            printf("*Benchmarking disabled*\n\n");

        #endif

        //set start time:
        clock_t start_time = clock();

        //run program
        PRM(&emitter_PRM_coords, sats, timestamps);

        //set end time:
        clock_t end_time = clock();

        //display performance summary
        clock_t PRM_runtime = end_time - start_time;
        double PRM_runtime_ms = (double)PRM_runtime * 1000 / CLOCKS_PER_SEC;
        printf("PRM complete in %f milliseconds\n", PRM_runtime_ms);

        #ifdef PRM_BENCHMARKING

            //int i;
            for (i = 0; (i < PRM_NUM_TIMESTAMPS) && (timestamps[i] != 0); i++)
            {
                clock_t timestamp_offset = timestamps[i] - start_time;
                double timestamp_offset_ms = (double)timestamp_offset * 1000 / CLOCKS_PER_SEC;
                printf("benchmark timestamp %d: %f milliseconds\n",i ,timestamp_offset_ms);
            }
        
        #endif

        //display calculation errors

        printf("\nEmitter calculated coords: \n\n");
        printf("\t x: %10d\n", emitter_PRM_coords.x);
        printf("\t y: %10d\n", emitter_PRM_coords.y);
        printf("\t z: %10d\n", emitter_PRM_coords.z);

        printf("\nEmitter true coords: \n\n");
        printf("\t x: %10d\n", emitter_true_coords.x);
        printf("\t y: %10d\n", emitter_true_coords.y);
        printf("\t z: %10d\n", emitter_true_coords.z);
        
        printf("\nEmitter coords absolute error: \n\n");
        printf("\t x: %10d\n", emitter_PRM_coords.x - emitter_true_coords.x);
        printf("\t y: %10d\n", emitter_PRM_coords.y - emitter_true_coords.y);
        printf("\t z: %10d\n", emitter_PRM_coords.z - emitter_true_coords.z);

    }
    //fclose(file);
    return 0;
}