#include <stdio.h>
#include <time.h>

#include "PRM.h"


//comment this line to disable benchmarking within the PRM algorithm
#define PRM_BENCHMARKING 

#ifdef PRM_BENCHMARKING
#define PRM_NUM_TIMESTAMPS 64 //TODO: figure out how many timestamps are needed
#endif

void setCoord(coord_t* coord, int32_t X, int32_t Y, int32_t Z){
    coord->x = X;
    coord->y = Y;
    coord->z = Z;
}

void getGPSData(GPS_data_t* satellite, coord_t coords, uint32_t time){
    setCoord(&(satellite->coord), coords.x, coords.y, coords.z);
    satellite->time = time; 
}

int main(){
    
    coord_t emitter_PRM_coords, emitter_true_coords;
    coord_t sat_coords[4];
    GPS_data_t sats[4];

/* create GPS data using assuming a general default satellite radius of 20,200km and an emmitter radius 
of 6,371km (earth radius) found through online search.This scenario is assuming a situation with 4 
satellites (A,B,C,D).  */

// test dataset generated by test_generator.py:

    setCoord(&sat_coords[0], -1348312774, -120003263, -1659032645);
    setCoord(&sat_coords[1], -718225637, -1491088156, -1358508550);
    setCoord(&sat_coords[2], -1245250017, -1440971133, -978617406);
    setCoord(&sat_coords[3], -350381710, -1525412884, -1461193220);
    setCoord(&emitter_true_coords, -202357496, -34399359, -643376510);

    getGPSData(&sats[0], sat_coords[0], 2071383592);
    getGPSData(&sats[1], sat_coords[1], 2299812882);
    getGPSData(&sats[2], sat_coords[2], 2407913067);
    getGPSData(&sats[3], sat_coords[3], 2305509064);

// end of test data

    #ifdef PRM_BENCHMARKING

        //initialize timestamp array for benchmarking
        clock_t timestamps[PRM_NUM_TIMESTAMPS] = {0}; 
        printf("*Benchmarking enabled*\n\n");

    #else 

        //create dummy timestamp array
        clock_t* timestamps = NULL; 
        printf("*Benchmarking disabled*\n\n");

    #endif

    //set start time:
    clock_t start_time = clock();

    //run program
    PRM(&emitter_PRM_coords, sats, timestamps);

    //set end time:
    clock_t end_time = clock();

    //display performance summary
    clock_t PRM_runtime = end_time - start_time;
    double PRM_runtime_ms = (double)PRM_runtime * 1000 / CLOCKS_PER_SEC;
    printf("PRM complete in %f milliseconds\n", PRM_runtime_ms);

    #ifdef PRM_BENCHMARKING

        int i;
        for (i = 0; (i < PRM_NUM_TIMESTAMPS) && (timestamps[i] != 0); i++)
        {
            clock_t timestamp_offset = timestamps[i] - start_time;
            double timestamp_offset_ms = (double)timestamp_offset * 1000 / CLOCKS_PER_SEC;
            printf("benchmark timestamp %d: %f milliseconds\n",i ,timestamp_offset_ms);
        }
    
    #endif

    //display calculation errors
    printf("\nEmitter coords absolute error: \n\n");
    printf("\t x: %d\n", emitter_PRM_coords.x - emitter_true_coords.x);
    printf("\t y: %d\n", emitter_PRM_coords.y - emitter_true_coords.y);
    printf("\t z: %d\n", emitter_PRM_coords.z - emitter_true_coords.z);

    return 0;
}