#include <stdio.h>
#include <time.h>
#include <string.h>
#include <assert.h>
#include "PRM.h"

//match this number with the number of tests wanting to be done/generated
#define total_test_cases 10

#define test_iterations 1000

#ifdef PRM_BENCHMARKING
    #define PRM_NUM_TIMESTAMPS 9 
#else
    #define PRM_NUM_TIMESTAMPS 0 
#endif

void setCoord(coord_t* coord, int32_t X, int32_t Y, int32_t Z){
    coord->x = X;
    coord->y = Y;
    coord->z = Z;
}

void getGPSData(GPS_data_t* satellite, coord_t coords, uint32_t time){
    setCoord(&(satellite->coord), coords.x, coords.y, coords.z);
    satellite->time = time; 
}



int main(){
    
    coord_t emitter_PRM_coords, emitter_true_coords;
    coord_t sat_coords[4];
    GPS_data_t sats[4];

/* create GPS data using assuming a general default satellite radius of 20,200km and an emmitter radius 
of 6,371km (earth radius) found through online search.This scenario is assuming a situation with 4 
satellites (A,B,C,D).  */

    // Read test dataset generated by test_generator.py:

    int32_t X_gen[5*total_test_cases], Y_gen[5*total_test_cases], Z_gen[5*total_test_cases], time_gen[5*total_test_cases];
    int satellite_id[5*total_test_cases];

    FILE *file = fopen("./test_gen.txt", "r");
    if (file == NULL){
        perror("Error opening this file");
        return 1;
    }

    char line[100];
    int i = 0;
    while (fgets(line, sizeof(line), file)) {

    // skip empty string lines
        if (strlen(line) <= 10) {
            continue;
        }
        /*
        printf("\n");
        printf("Read line: %s\n"  , line);
        */

    // Scan in data from file, format of the generated data is: "satellite_id X Y Z time"
        //int X_gen[total_tests], Y_gen[total_tests], Z_gen[total_tests], time_gen[total_tests];
        assert(sscanf(line, "%d %d %d %d %d", &satellite_id[i], &X_gen[i], &Y_gen[i], &Z_gen[i], &time_gen[i]) == 5);

        /*
        printf("\n");
        printf("Processed line: %s\n", line);
        */
        
    // Show data values for each test set
        //printf("Test iteration for Satellite %d:\n", satellite_id[i]);
        //printf("X: %d, Y: %d, Z: %d, Time: %d\n", X_gen[i], Y_gen[i], Z_gen[i], time_gen[i]);
        i++;
        //printf("%d \n", i);
    }
    fclose(file);

    double timestamp_sums[PRM_NUM_TIMESTAMPS];
    double runtime_sum;

    #ifdef PRM_BENCHMARKING

        //initialize timestamp array for benchmarking
        struct timespec timestamps[PRM_NUM_TIMESTAMPS] = {0}; 
        printf("\n*Benchmarking enabled*\n\n");

    #else 

        //create dummy timestamp array
        struct timespec* timestamps = NULL; 
        printf("*Benchmarking disabled*\n\n");

    #endif
    
    // run tests a bunch of times to get an average runtime
    int test_iteration;
    for (test_iteration = 0; test_iteration < test_iterations; test_iteration++)
    {

    // Use a loop that iterates by 5 each time due to how the satellites are stored in the arrays
        int test_num_tracker;
        for(test_num_tracker = 0; test_num_tracker < total_test_cases * 5; test_num_tracker+=5){

            setCoord(&sat_coords[0], X_gen[test_num_tracker], Y_gen[test_num_tracker], Z_gen[test_num_tracker]);
            setCoord(&sat_coords[1], X_gen[test_num_tracker + 1], Y_gen[test_num_tracker + 1], Z_gen[test_num_tracker + 1]);
            setCoord(&sat_coords[2], X_gen[test_num_tracker + 2], Y_gen[test_num_tracker + 2], Z_gen[test_num_tracker + 2]);
            setCoord(&sat_coords[3], X_gen[test_num_tracker + 3], Y_gen[test_num_tracker + 3], Z_gen[test_num_tracker + 3]);
            setCoord(&emitter_true_coords, X_gen[test_num_tracker + 4], Y_gen[test_num_tracker + 4], Z_gen[test_num_tracker + 4]);
            
            getGPSData(&sats[0], sat_coords[0], time_gen[test_num_tracker]);
            getGPSData(&sats[1], sat_coords[1], time_gen[test_num_tracker + 1]);
            getGPSData(&sats[2], sat_coords[2], time_gen[test_num_tracker + 2]);
            getGPSData(&sats[3], sat_coords[3], time_gen[test_num_tracker + 3]);

        // end of test data

            struct timespec start, end;

            //set start time:
            clock_gettime(CLOCK_MONOTONIC, &start);
            //run program
            PRM(&emitter_PRM_coords, sats, timestamps);
            //set end time:
            clock_gettime(CLOCK_MONOTONIC, &end);

            double PRM_runtime =    (double)(end.tv_sec - start.tv_sec) + 
                                    (double)(end.tv_nsec - start.tv_nsec) / 1000000000;
            runtime_sum += PRM_runtime;

            int tstmp_idx;
            for (tstmp_idx = 0; tstmp_idx < PRM_NUM_TIMESTAMPS; tstmp_idx++)
            {
                double section_runtime = (double)(timestamps[tstmp_idx].tv_sec  - start.tv_sec) + 
                                         (double)(timestamps[tstmp_idx].tv_nsec - start.tv_nsec) / 1000000000;
                timestamp_sums[tstmp_idx] += section_runtime;
            }
        }

        // last itteration: display calculation errors

        printf("\nEmitter calculated coords: \n\n");
        printf("\t x: %10d\n", emitter_PRM_coords.x);
        printf("\t y: %10d\n", emitter_PRM_coords.y);
        printf("\t z: %10d\n", emitter_PRM_coords.z);

        printf("\nEmitter true coords: \n\n");
        printf("\t x: %10d\n", emitter_true_coords.x);
        printf("\t y: %10d\n", emitter_true_coords.y);
        printf("\t z: %10d\n", emitter_true_coords.z);
        
        printf("\nEmitter coords absolute error: \n\n");
        printf("\t x: %10d\n", emitter_PRM_coords.x - emitter_true_coords.x);
        printf("\t y: %10d\n", emitter_PRM_coords.y - emitter_true_coords.y);
        printf("\t z: %10d\n", emitter_PRM_coords.z - emitter_true_coords.z);

    }

    // average time measurements
    int tstmp_idx;
    for (tstmp_idx = 0; tstmp_idx < PRM_NUM_TIMESTAMPS; tstmp_idx++)
    {
        timestamp_sums[tstmp_idx] /= (test_iterations * total_test_cases);
    }

    runtime_sum /= (test_iterations * total_test_cases);

    //display performance summary
    printf("\n-------PERFORMANCE SUMMARY-------\n");


    #ifdef PRM_BENCHMARKING
        int j;
        printf("\nbenchmark timestamps:\n");
        for (j = 0; j < PRM_NUM_TIMESTAMPS; j++)
        {
            printf("%f microseconds\n", timestamp_sums[j] * 1000000);
        }
        // printf("benchmark timestamp %d was 0", j);        
    #endif

    printf("Average PRM runtime: %f microseconds\n", runtime_sum * 1000000);

    //fclose(file);
    printf("\n--------------END--------------\n");
    return 0;
}